version: "3"

tasks:

  composer:
    aliases: [ c ]
    desc: "Install the composer dependencies."
    cmds:
      - composer update
    sources:
      - composer.json
      - composer.lock
    generates:
      - ./vendor/**/*

  test:
    aliases: [ t ]
    desc: "Run the unit tests."
    deps: [ composer ]
    cmds:
      - ./vendor/bin/pest

  scan:
    aliases: [ s ]
    desc: "Run the static code analysis."
    deps: [ composer ]
    cmds:
      - ./vendor/bin/phpstan analyse --memory-limit 512M
