version: "3"

tasks:

  composer:
    aliases: [ c ]
    desc: "Install the composer dependencies."
    cmds:
      - composer install
    sources:
      - composer.json
      - composer.lock
    generates:
      - ./vendor/**/*

  format:
    aliases: [ f ]
    desc: "Format the source code."
    deps: [ composer ]
    cmds:
      - ./vendor/bin/php-cs-fixer fix src

  scan:
    aliases: [ s ]
    desc: "Run the static code analysis."
    deps: [ format ]
    cmds:
      - ./vendor/bin/phpstan analyse --memory-limit 256M

  test:
    aliases: [ t ]
    desc: "Run the unit tests."
    deps: [ scan ]
    cmds:
      - ./vendor/bin/pest

  licenses:
    aliases: [ l ]
    desc: "Generate the license overview file."
    deps: [ composer ]
    cmds:
      - ./vendor/bin/php-legal-licenses generate
      - mv licenses.md ./docs
