name: PR

on: [pull_request]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json & composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Format
        run: vendor/bin/php-cs-fixer fix src

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        if: always()
        with:
          commit_message: "Apply php-cs-fixer changes"
          branch: ${{ github.head_ref }}

  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    name: PHP ${{ matrix.php-versions }} code analysis on ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: phpunit:${{ matrix.phpunit-version }}, composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json & composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Analyse
        run: vendor/bin/phpstan analyse --memory-limit 512M
