name: PR

on: [pull_request]

jobs:

  check:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
    name: PHP ${{ matrix.php-versions }} code analysis on ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: phpunit:${{ matrix.phpunit-version }}, composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json & composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run Static Code Analysis
        run: vendor/bin/phpstan analyse --memory-limit 512M
